### ISSUE TITLE
Admin screen heading tags with Wordpress 4.5

### ISSUE THREAD

**Issue by lutrov** [justintadlock/members#100]
Just a gentle reminder that all Wordpress headings in admin screens have changed from H2 to H1, H3 to H2, etc in version 4.3, back in July 2015. Please consider changing your heading structure so it's semantically correct.

For instance, in `admin/class-user-edit.php`:

`<h3><?php esc_html_e( 'Roles', 'members' ); ?></h3>`

Should be:

`<h2><?php esc_html_e( 'Roles', 'members' ); ?></h2>`

**Comment by justintadlock** [comment]
If you want to go through and find all the headings that need changing, I'll be happy to update them.

**Comment by lutrov** [comment]
It's just these two:

* `admin/class-cap-tabs.php`: `<h3><?php printf( esc_html__( 'Edit Capabilities: %s', 'members' ), '<span class="members-which-tab"></span>' ); ?></h3>`
* `admin/class-user-edit.php`: `<h3><?php esc_html_e( 'Roles', 'members' ); ?></h3>`

Should be `H2` in both cases.
