### ISSUE TITLE
Gravity Forms Addon Page Hidden By Members

### ISSUE THREAD

**Issue by andywarren** [justintadlock/members#102]
Hi Justin,

I installed https://github.com/bradyvercher/gravity-forms-iframe and noticed that its settings page is hidden when Members is activated. All capabilities are granted in Members as well. I had found this: https://github.com/bradyvercher/gravity-forms-iframe/issues/15 in the issues for that plugin, and also added a comment there regarding this, but I wanted to reach out to you to see if you know of a reason or fix that Members would block the GF addon even if there isn't any code in the addon integrating it with Members. Any suggestions would be greatly appreciated!

**Comment by justintadlock** [comment]
Members doesn't hide or show stuff.  It simply provides access to capabilities.  So, you'll need to get in touch with the add-on plugin author or the GF plugin author to determine how to set things up.  It's my understanding that GF has some custom code that executes when Members is activated.  However, I don't personally use the plugin, so I'm unfamiliar with how that's set up.

**Comment by andywarren** [comment]
Thanks for the reply. That makes sense. If the addon developer replies back I'll post here again just for future reference for others. Thanks again.

**Comment by andywarren** [comment]
The Gravity Forms Iframe addon developer has pushed a fix for this issue. You can read about it here: https://github.com/bradyvercher/gravity-forms-iframe/issues/15#issuecomment-230578762
