### ISSUE TITLE
Manager users screen: Add/Remove role

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#103]
Currently, WordPress has a "Change role to" option on the manage users screen.  This doesn't go so well with multiple roles per user.

When multiple roles is enabled, we need to hide the "Change role to" select and "Change" button (no way to filter these).  Then, we need to hook into `restrict_manage_users` and add the following new fields:
- Add role `<select>` with button
- Remove role `<select>` with button

**Notes:**
- Don't show uneditable roles in the select drop-down.
- User needs the `promote_users` cap to see the fields.
- Check against `current_user_can( 'promote_user', $user_id )` for promoting specific users.

**Comment by justintadlock** [comment]
❤️

**Comment by renatonascalves** [comment]
That's fantastic! I had a problem in my site for not understanding that WordPress literally changes the role and wipes out the rest (the additional ones)... That's a nice addition, for sure.
