### ISSUE TITLE
Clash with Gravity Forms?

### ISSUE THREAD

**Issue by gyrus** [justintadlock/members#104]
I just encountered an issue where a was unable to access the Import Forms tab under Forms > Import / Export, using Gravity Forms.

I deactivated all my plugins and found that Members was causing the issue. The permissions check in GF's `export.php` uses its own cap check:

`GFCommon::current_user_can_any( 'gravityforms_create_forms' )`

Looking at that method in `common.php`, I saw a reference to a cap called `gform_full_access`. I went into Members and added that as a custom capability, and I now seem to be able to import.

I realise you might say this is a GF issue, but obviously they will say it's a Members issue. The fact is it's GF functionality that works when Members is deactivated. Also, I'm not sure if my 'fix' is the right way of going about it (I'm not sure why `gform_full_access` exists, not why it has to be added as custom cap) - maybe I'm covering over a more subtle issue with a blunt fix?

**Comment by justintadlock** [comment]
GF intentionally doesn't add some capabilities when Members is active to put you in full control of the situation.

Here's their role management guide: https://www.gravityhelp.com/documentation/article/role-management-guide/

**Comment by justintadlock** [comment]
FWIW, I plan to write a good guide for plugin authors to integrate with this plugin in the near future.  Maybe GF will use it and make the experience a little better.

**Comment by gyrus** [comment]
Well that's certainly a feature and not a bug! Many thanks.
