### ISSUE TITLE
Restrict to which roles a user can switch

### ISSUE THREAD

**Issue by tnoguero** [justintadlock/members#105]
Hi

Is there any way to restrict to which other roles a specific roles can switch to?. I.e. I have contributor that would like to see how a student or other roles would see the site but I don't want them to switch to an user with admin role.

Thanks
Teresa

**Comment by justintadlock** [comment]
You'll need to look into a user-switching plugin.  I've thought about building a role-switching plugin too.

Anyway, this is not something in the Members plugin.
