### ISSUE TITLE
Certain menu items cannot be hidden

### ISSUE THREAD

**Issue by invot** [justintadlock/members#112]
There aren't clear instructions on how to create working custom instructions. I'd like to hide the entirety of the "appearance" and "settings" tabs in the backend. How would that be done? I seem to remember that authors and editors aren't able to see these things, but since installing this plugin, I can't get to wp-admin/index.php without setting the role to admin. Was that intentional?

**Comment by justintadlock** [comment]
This is an issue tracker.  The support forum is located here: http://themehybrid.com/board/topics
