### ISSUE TITLE
Mail not sent on role change with Members active

### ISSUE THREAD

**Issue by codente** [justintadlock/members#113]
I'm having the same problem as here 
https://wordpress.org/support/topic/issue-with-set_user_role-action-hook/

Is there any solution to this?

**Comment by justintadlock** [comment]
See sticky topic: https://wordpress.org/support/topic/changing-role-no-longer-fires-the-set_user_role-hook/

**Comment by codente** [comment]
You rock, Justin!  Sorry to bother you with this :)

**Comment by justintadlock** [comment]
No problem. :)
