### ISSUE TITLE
Using Custom Templates for pages

### ISSUE THREAD

**Issue by Stoney64** [justintadlock/members#115]
Hi there!

First of all, thanks for your great work.
I'm having some issues with a page in which I'm using a custom template. Although I set up restrictions, the page is visible for everyone to see. The page behaves correctly if I use the standard template.
Is there some code I should paste in my template?
Thanks in advance for your time.

Stoney

**Comment by justintadlock** [comment]
Closing this as `invalid` because this is a support question and not a issue.
