### ISSUE TITLE
Theme is blocking content - shortcode request [allow_all]

### ISSUE THREAD

**Issue by flashybits** [justintadlock/members#118]
I have a condition where the theme i'm using is adding content to the homepage by it's own [shortcodes] but what's happening is when a user is not logged in, the homepage content sections are being blocked, it works when the user is logged in...

So Is there a shortcode I could wrap this section content in that could always allow the content - kind of like the reverse of the existing shortcode [members_access]

any help appreciated...

**Comment by justintadlock** [comment]
This sounds like a theme-related issue.  If you dig into it a bit more and can find an issue with Members, I'll open it back up.
