### ISSUE TITLE
 role is not editable. This means that it is most likely added via another plugin for a special use or that you do not have permission to edit it.

### ISSUE THREAD

**Issue by joelbrennan0** [justintadlock/members#127]
I have a website in production environment where a number of roles have become un-editable, with the above error message being displayed.

Can anyone offer advice on possible cause / solution please?

**Comment by klihelp** [comment]
@joelbrennan0  How did you resolve?
cc - @justintadlock

**Comment by joelbrennan0** [comment]
Hi

I can't remember off the top of my head. I think the conflicts occurred
from bbpress another plugin that had been installed. I amended the
conflicts.

Thanks

**Comment by klihelp** [comment]
resolved, In my case a plugin's filter turned some roles into un-editable.
