### ISSUE TITLE
Expose user levels

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#13]
When I first created this plugin, user levels had already been deprecated for a long time in core.  There was one exception with the author drop-down, which I was told would be fixed by now.  But, it's still lingering around:
http://core.trac.wordpress.org/ticket/16841

Members originally hid user levels from the edit role screen so that users could report issues with plugins that were still using them.  I haven't gotten a report on this in a long while and have been able to help several plugin authors in the past.  Good job by plugin authors!

But, WordPress is still the problem.  Basically, when you create new user roles, they need to be assigned a level to appear in the author drop-down on the edit post screen.  For most users, this hasn't been an issue.  I still get the occasional support question on this though.

Therefore, I'm probably going to add a checkbox (on the settings page) to show user levels on the edit role screen (disabled by default).

**Comment by kraftner** [comment]
You might consider showing them as disabled check-boxes in any case. It took me some time to find out that the reason a role I created with exactly the same caps as editor was still showing a different count. Another option would be to decrease the count on the user role list. As it is now it is confusing.

**Comment by justintadlock** [comment]
User levels moved to a separate plugin: http://themehybrid.com/plugins/members-role-levels
