### ISSUE TITLE
Implement Visual Composer (or any shortcode content loader) 

### ISSUE THREAD

**Issue by ensemblebd** [justintadlock/members#132]
Visual Composer and Cornerstone pages/posts/categories/tax are visible (contents contain "Access Denied") when they should be entirely hidden due to restrictions. And furthermore, other dynamic content loaders (live search, grid views, etc) show full contents when they shouldn't show anything. So if you display categories, it will list 10 articles for example, all of which would contain "Access Denied".

So I'm planning to make a pull request for that off the dev branch for consideration.
See pull https://github.com/justintadlock/members/pull/133

**Comment by justintadlock** [comment]
Pretty much anything mentioning Visual Composer is going to be a firm no.  Feel free to open up some tickets with any specific issues you find.
