### ISSUE TITLE
add_user_role fires twice with already existing role

### ISSUE THREAD

**Issue by arminus** [justintadlock/members#134]
According to [this](http://themehybrid.com/board/topics/email-notification-when-only-user-role-changed#post-8309), add_user_role should fire each time a new role is **added** to a user. 

What I'm observing, though is that it fires twice in case I add a single role to that user, first with the actually added role in the 2nd param, then with the already existing role. Is this a bug or a feature?

(in my case, I need to respond to a specific role being added which I can't seem to reliably detect this way)

**Comment by justintadlock** [comment]
Can you test this on the `dev` branch?  Also, share sample code if you have it.

**Comment by justintadlock** [comment]
@arminus - I'd like to see if we can get this in time for the 2.0.0 release.  Can you test on the `dev` branch and provide further feedback?

**Comment by justintadlock** [comment]
I'm closing this as fixed.  I can't replicate the issue on the current development branch.

**Comment by arminus** [comment]
@justintadlock I confirm that this works as expected in the dev branch

**Comment by justintadlock** [comment]
Awesome!  Thanks for confirming.
