### ISSUE TITLE
Notice error

### ISSUE THREAD

**Issue by spacedmonkey** [justintadlock/members#136]
Getting the following php notice error on the front end. Version 1.1.3

![screen shot 2017-06-21 at 17 06 53](https://user-images.githubusercontent.com/237508/27394494-419167c8-56a4-11e7-9272-a3923f3df1d4.png)

**Comment by justintadlock** [comment]
This is an issue caused by either your theme or another plugin on your site incorrectly calling `the_content` filter hook.  More info: https://themehybrid.com/weblog/how-to-apply-content-filters
