### ISSUE TITLE
assets directory for the screenshots

### ISSUE THREAD

**Issue by mustafauysal** [justintadlock/members#138]
I just realized that screenshots are exists on [SVN trunk](https://plugins.svn.wordpress.org/members/trunk/). @justintadlock could you move them to `assets` :)

**Comment by justintadlock** [comment]
I'm undecided on this.  Part of me wants to keep them in the main plugin so that they're distributed to users who might want to view the screenshots with the `readme.txt` context.

**Comment by justintadlock** [comment]
I may revisit this in the future, but I think I'd prefer to package them with the plugin for the time being.
