### ISSUE TITLE
Update Failed (from 1.1.3 to 2.0)

### ISSUE THREAD

**Issue by colomet** [justintadlock/members#141]
function MeterToPixel(){ var meter = document.getElementById("m_1_50").value; var answer = meter * 113.385; document.getElementById("m2px_1_50").value = answer; } function PixelToMeter(){ var pixel = document.getElementById("px_1_50").value; var answer = pixel / 113.385; document.getElementById("px2m_1_50").value = answer; } function MeterToPixel2(){ var meter = document.getElementById("m_1_250").value; var answer = meter * 22.677; document.getElementById("m2px_1_250").value = answer; } function PixelToMeter2(){ var pixel = document.getElementById("px_1_250").value; var answer = pixel / 22.677; document.getElementById("px2m_1_250").value = answer; } {"success":true,"data":{"update":"plugin","slug":"members","oldVersion":"Version 1.1.3","newVersion":"Version 2.0.0","plugin":"members\/members.php","pluginName":"Members"}}

**Comment by justintadlock** [comment]
I have no idea what any of that means.  An explanation would help.

**Comment by colomet** [comment]
It was a message I get in the header of the plugins page after the update of the plugin. But now, looks like it works.
