### ISSUE TITLE
Can't remove role in 2.0

### ISSUE THREAD

**Issue by michaeltorbert** [justintadlock/members#145]
After updating to 2.0, I can't remove a role from a user in user-edit.php.

I also get the following notice:
PHP Notice:  Undefined variable: user in /public_html/wp-content/plugins/members/admin/class-user-edit.php on line 175
PHP Notice:  Trying to get property of non-object in /public_html/wp-content/plugins/members/admin/class-user-edit.php on line 175

When I swap 2.0 out with the previous version, I can again.

(Update, if a user has multiple roles, I can remove all but one of them. I only can't remove the last one.)

**Comment by justintadlock** [comment]
Looks like I forgot to change `$user` to `$old_user_data` on that line in this commit: https://github.com/justintadlock/members/commit/60b43976a315bd376b76f05999dca89bde6186f2

**Comment by justintadlock** [comment]
If you can give the 2.0 branch a test and confirm that it works for you, we can close out this ticket. https://github.com/justintadlock/members/tree/2.0

**Comment by michaeltorbert** [comment]
@justintadlock Works for me. Thank you. :)

**Comment by justintadlock** [comment]
👍
