### ISSUE TITLE
Help! Error message when clicking members only when not logged in

### ISSUE THREAD

**Issue by GeoTran** [justintadlock/members#151]
I am getting the following error message when not logged in:
Warning: Cannot modify header information - headers already sent by (output started at /home/georgetranos/public_html/new.obony.org/wp-content/themes/display/members.php:11) in /home/georgetranos/public_html/new.obony.org/wp-content/themes/display/members.php on line 197

When logged in, I do not get the error and it takes me right to my members only page. Please help!

Thanks, George

This is my members.php file:

<?php

/*

Template Name: Members

*/

?>

<?php if ( $user_ID ) : // if logged in ?>

<?php

global $k_option; 

$k_option['custom']['bodyclass'] = ""; // $k_option['custom']['bodyclass'] = "class='fullwidth'";

get_header(); 

?>				

<div id="main">

	<div id="content">		

			<?php

			if (have_posts()) : 

			while (have_posts()) : the_post();

				// check if we got a previe picture, and which one should be taken 

				// (image resizing with "tim thumb" on? then we can take the big one and resize it)

				$preview_small = get_post_meta($post->ID, "_preview_small", true);

				$preview_medium = get_post_meta($post->ID, "_preview_medium", true);

				$preview_big = get_post_meta($post->ID, "_preview_big", true);

				

				//defaults:

				$preview = $preview_medium;

				$link_url = $preview_big;

				$lightbox = 'singlepost';

				$link = true;

				//change if necessary:

				

				// resizing? => take next sized picture

				if ($k_option['general']['tim'] == "1" && $preview_medium == "") 

				{ 

					$preview = $preview_big;

				} 

				

				// no bigpicture? => no lightbox

				if ($preview_big == "") { $lightbox = ''; $link = true; $link_url = get_permalink(); } 

				// the kriesi_build_image function used here checks if the image should be resized. 

				// the function is located in framework/helper_functions

				$preview = kriesi_build_image(array('url'=>$preview,

													'height'=> '273',

													'width'=> '610',

													'lightbox'=>$lightbox,

													'link'=>$link,

													'link_url'=>$link_url

													));		

			

			?>

		<div class='entry blogentry'>

		

			<div class="date">

   				<span class='day'><?php the_time('d') ?></span>

   				<span class='month'><?php the_time('M') ?></span>

   				<span class='year'><?php the_time('Y') ?></span>

			</div>

			<h2><a href="<?php echo get_permalink() ?>" rel="bookmark" title="Permanent Link: <?php the_title(); ?>"><?php the_title(); ?></a></h2>

				

			<div class='post_data'>

				<span class='categories'><?php the_category(', ') ?><?php edit_post_link('Edit', ', ', ''); ?></span>

				<span class='author'><?php comments_popup_link('No Comments', '1 Comment', '% Comments'); ?></span>

			</div>

			

		<?php

		echo $preview; // echo the preview image

		the_content('Read more');  

		?>

	</div>

	<div class='entry commententry'>

           		<?php comments_template(); ?>

           		</div>	

	<?php 	endwhile; 

	

				kriesi_pagination($query_string);

				else: 

		?>

			<div class="entry">

			<h2>Nothing Found</h2>

			<p>Sorry, no posts matched your criteria.</p>

			</div>

 	<?php

			endif;

	?>  

</div>

<?php get_sidebar(); ?>

</div>

<?php get_footer();  ?>

<?php else : // if not logged in go to the "Not a Member?" page. Its url is "not-a-member".

$url = 'not-a-member';

header("Location:$url"); 

endif; // end if logged in

?>

**Comment by justintadlock** [comment]
This is unrelated to the Members plugin, so I'm closing this ticket.

However, I do have a help and support site that you are more than welcome to sign up for:  https://themehybrid.com

**Comment by GeoTran** [comment]
I am using the members plugin! I had to change my site recently to upgrade it. I thought this coding was from your plugin.

**Comment by justintadlock** [comment]
The above errors you posted and the code are both unrelated to the plugin.
