### ISSUE TITLE
Add parameter to the [members_login_form] shortcode or the login form widget

### ISSUE THREAD

**Issue by aimgeiks** [justintadlock/members#152]
I would like to make the login and password fields more iclear for the users, at least put a background, is there any way to do that ? Right now it is note very clear to see where to type.
![capture d ecran 2017-08-20 a 13 50 01](https://user-images.githubusercontent.com/31181544/29494627-8e19c6e2-85ae-11e7-9066-d4ab10144b0b.png)

**Comment by justintadlock** [comment]
This is an issue with your theme.  You'll need to ask your theme designer to add in appropriate styles for form fields.  These are basic HTML elements that should be accounted for in any theme.
