### ISSUE TITLE
Certain plugin permissions not available

### ISSUE THREAD

**Issue by marketingmagi** [justintadlock/members#154]
Greetings, while using Members role permissions, I cannot affect permissions for Caldera Forms, nor MailPoet 3 plugins. As these are newly available, must you manually add their hooks to your Members plugin?

**Comment by justintadlock** [comment]
You'll need to contact those plugin authors if you're looking for any particular capabilities they have. 

Outside of that, feel free to join [Theme Hybrid](https://themehybrid.com/club) if you have support questions you need help with or want me to dig into third-party plugin code.
