### ISSUE TITLE
Function members_user_has_cap_filter raises ArgumentCountError on PHP7.1

### ISSUE THREAD

**Issue by t-ionut** [justintadlock/members#159]
I have tried the following scenario:

1. Create a user with Editor role
2. Log into wp-admin with that user's credentials
3. End up in an error screen. Logs show the following:
```
PHP Recoverable Error: Uncaught exception 'ArgumentCountError' with message 'Too few arguments to function members_user_has_cap_filter(), 3 passed in /www/wp-includes/class-wp-hook.php on line 298 and exactly 4 expected' in /www/wp-content/plugins/members/inc/functions-users.php on line 34, request: GET /wp-admin/
```

I'm not sure if it's limited to one user role, but it surely is a PHP 7.1 incompatibility issue.

**Comment by justintadlock** [comment]
Can you disable all other plugins and test, please?

**Comment by t-ionut** [comment]
My mistake, it was a third party plugin calling the `user_has_cap` filter with only 3 args.
