### ISSUE TITLE
Changing user roles doesn't change access

### ISSUE THREAD

**Issue by jwilliquette** [justintadlock/members#160]
I'm having some difficulty with some of my users on the website. I've given them admin permissions, but it doesn't give them access to any of the site pages. I tried giving access to specific page genres, and it actually took away their permissions. I tried removing and redoing the user, but that didn't fix the issue. 

Any thoughts?

**Comment by justintadlock** [comment]
This is the code issue tracker for the plugin.  Support is handled via https://themehybrid.com/club
