### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by foscone** [justintadlock/members#161]
Hi, I developed a site before it had a domain, working via ip address. Now I did point the domain to ip address and changed the address in the wordpress settings. Doing this I closed out, I can login but I can't access to admin area. Why member plugin did so? How can I solve this issue?
I changed wordpress address via wp-config.php because I could not access, maybe it's not the address the problem but before it changed it all worked well.
Thanks.
Fosco

**Comment by justintadlock** [comment]
You're in the wrong place.  This doesn't have anything to do with the Members plugin.

**Comment by foscone** [comment]
OK. Anyway, is there a way to reset capabilities and deactivate members plugin without login?

**Comment by foscone** [comment]
My problem was permissions problem, I solved it whit this guide https://developer.wordpress.org/cli/commands/role/reset/
What is the correct way to uninstall members plugin and use native wordpress users?
