### ISSUE TITLE
Get User's Roles

### ISSUE THREAD

**Issue by cgidds** [justintadlock/members#165]
Is there a way to get all roles assigned to a user? We're migrating from the Groups plugin to the Members plugin and trying to retrofit existing code to the new plugin. Thanks.

**Comment by justintadlock** [comment]
@cgidds - Yes, it's possible to get all of a user's roles.  If you need help, I run support at [Theme Hybrid](https://themehybrid.com).

I'm going to close this ticket simply because it's not a bug or feature request.
