### ISSUE TITLE
PHP Notice:  Trying to get property of non-object in members/inc/template.php on line 95

### ISSUE THREAD

**Issue by ahmed-sigmalux** [justintadlock/members#166]
I'm seeing this error hundreds of times in our debug.log:

`
PHP Notice:  Trying to get property of non-object in /var/www/wordpress/wp-content/plugins/members/inc/template.php on line 95`

**Comment by justintadlock** [comment]
This is a problem with one of your plugins or your theme incorrectly calling the `the_content`, `the_excerpt`, or a related filter hook.  Here's the details: https://themehybrid.com/weblog/how-to-apply-content-filters

If you need help fixing the problematic themes and/or plugins, feel free to sign up for [support at Theme Hybrid](https://themehybrid.com).
