### ISSUE TITLE
conflict with bbPress since v2

### ISSUE THREAD

**Issue by ChrisHe** [justintadlock/members#167]
It appears that v2.0.0 update has broken bbPress forum capabilities. 
A user cannot write a reply to a topic.
Although  these are checked: 
Users.Roles.Topics: "publish_topics, "edit_topics"
Users.Roles.Replies:  "publish replies" and "edit replies"

(Disabling Members plugin then allows this)
Any news/agree?
Thanks
Chris

**Comment by justintadlock** [comment]
Members does not control what happens when a user+role has a specific capability.  It merely allows you to grant, deny, or not add a capability to a role.  It has no knowledge of capabilities beyond that.  You'll need to talk to the bbPress plugin author about the issue.

**Comment by renatonascalves** [comment]
I have a community with bbPress and Members and don't see this issue! I think it is unrelated to Members.

**Comment by ChrisHe** [comment]
Thanks for the quick response - @justintadlock I understand what you say, and will explore the issue further on the site. @renatonascalves - thanks for the input, sound like something else going on!
Best Regards
