### ISSUE TITLE
Backend admin language setting

### ISSUE THREAD

**Issue by emmtre** [justintadlock/members#168]
Can you please fix so the plugin respect the backend admin language setting for users. Now the admin language is always the frontend language which isn't the best for multilingual sites where you often want the admin to be in English even though the site is in French.

**Comment by justintadlock** [comment]
Closing this because this plugin doesn't have anything to do with language settings.

**Comment by emmtre** [comment]
It sure does since the plugin doesn't respect the admin language setting per user. Can I send you some screenshots? When you have lets's say a website in French and you choose English as the admin language you still get all admin in French for the Members plugin.

**Comment by justintadlock** [comment]
Screenshots wouldn't help.  If you want to provide some step-by-step instructions on how to replicate your issue, I'll be happy to test it out and determine if there's a problem with Members.

**Comment by emmtre** [comment]
1. Install WordPress in any language except in English
2. Go to Your Profile and chose English (US) as admin language
3. Go to Members Settings or Roles in Users
4. The admin language for Members in not in English

**Comment by justintadlock** [comment]
I tested this out.  Nearly all of the plugins I had installed (not my own) exhibited the same behavior.  I'm inclined to believe this is a bug in core WordPress itself.  I'll do some more digging when I get a chance.

In the meantime, I did figure out that if you installed the language in the `members/lang` folder instead of your `wp-content/languages/plugins` folder, it worked as it should.  I had the same success with other plugins.

**Comment by emmtre** [comment]
OK good to know that you managed to see the problem yourself. It could be a bug in core WordPress since I don't remember this behaviour before? But I'm running a lot of other plugins like Yoast SEO, ACF Pro, Admin Columns, Envira Gallery, WP Forms, etc on various multilingual sites and Members is the only one with this issue right now. I'll try to move the language files in the meantime. Many thanx and keep up the good work with Members!
