### ISSUE TITLE
[BUG] Capability counter is wrong - showing more

### ISSUE THREAD

**Issue by sparky672** [justintadlock/members#17]
Viewing the "Roles" screen under the "Users" menu...

By default, the "Contributor" Role is supposed to have THREE capabilities, yet this plugin is showing "5" in the "capabilities" column. When I click "edit" I only see the three defaults.

By default, the "Subscriber" Role is supposed to have ONE capability, yet this plugin is showing "2" in the "capabilities" column. When I click "edit" I only see one (default: read).

The WooCommerce "Customer" Role is supposed to have the same capabilities as "Subscriber" Role, which is ONE... but "3" is shown in the "capabilities" column. Then when I click on "edit" I only see one capability (default: read). I edited it to add two more capabilities and went back to the Roles screen where it still shows "3" capabilities although I just added two! I added two, so why doesn't it show five and what happened to the two that were apparently hidden?

This is scary stuff... are there hidden capabilities and did this plugin just delete them? What's really happening here?

Thank-you.

**Comment by redactuk** [comment]
If there are hidden capabilities, perhaps you could hard code a count modifier for each fixed capability? Example: Subscriber role count = actual capability count -1

**Comment by justintadlock** [comment]
Already taken care of on the `dev` branch.
