### ISSUE TITLE
Connecting with WooCommerce?

### ISSUE THREAD

**Issue by paaljoachim** [justintadlock/members#170]
Hi Justin

It would be great to be able to connect Members with WooCommerce.

Case study. A non profit I am working with needs a registration process with a members function to where the user pays a fee to become a member and can then also also purchase the bags with organic vegetables/meat and dairy. 

Have a great day Justin.

**Comment by justintadlock** [comment]
What exactly are you asking?  Members + WooCommerce should get along just fine out of the box.

**Comment by JulienMelissas** [comment]
I can confirm it works great out of the box. I think what @paaljoachim might be looking for is maybe one of WooCommerce' membership plugins? And maybe a user signup form? There are plenty out there of both...

**Comment by paaljoachim** [comment]
Hmm... I was a bit toooo quick on the draw here. Sorry about that.
Thinking that Members offered subscription levels, payment etc. But as I read the description in the WP repo and the web site I see that Members has to do with creating user roles and creating limits on what each role can access.

That means this issue is just some hot air rising into the air and can be closed.

I was thinking I could use Members for the non profit WooCommerce site that I am creating but from reading the description Members is a different plugin then I thought. Thanks for your time guys...
