### ISSUE TITLE
Login issue on mobile devices varying browsers

### ISSUE THREAD

**Issue by OllieGit** [justintadlock/members#172]
Are there any known issues with front end login using the Membership widget on mobile devices? Testing Chrome on Android, not a problem. Testing Safari on iOS or Android Internet, our login page appears to log in the user (recorded with Wordfence) but the login page refreshes.

All seems fine on desktop - tried solutions, deactivating plugins, checking theme functions file and general theme potential issues.

**Comment by justintadlock** [comment]
What do you mean by "Membership widget"?  Are you referring to the "Login" widget provided by Members?

The login page itself is something that core WP controls and is not a feature of the plugin.

**Comment by justintadlock** [comment]
Yeah, the Members login widget does not actually handle any of the login functionality.  It merely calls the WordPress `wp_login_form()` function.  Other than that, it doesn't really have any control on what happens.

**Comment by OllieGit** [comment]
Ok cheers Justin - really appreciate the speedy response in any case!
