### ISSUE TITLE
Clarify docs on "neither" permission

### ISSUE THREAD

**Issue by courtneyschwartz** [justintadlock/members#178]
Either a UI tweak or docs tweak (or both) could help here:

https://github.com/justintadlock/members/blob/master/readme.md#grant-deny-or-neither

In a similar plugin such as "User Role Editor," permissions are very clear: allow vs. deny It's basically a radio button, binary type of setting.

That's what users expect, maybe w/ a clear hierarchy for overrides if users have multiple roles.

But in Members, it's checkboxes and there is a third category: "neither".  What does that mean? In a config with that option, is there is a security hole or not? Neither the UI nor the doc nor trial-and-error leaves me confident.

It _sounds_ like it might be functionally equivalent to "Block," but then why does "neither" exist?

It sounds like it might actually have nothing to do w/ permissions but rather with visibility. But then why is it where permissions are being assigned? 

So I'm not sure what to do with it. More importantly, I'm not confident I can use it to achieve my permissions overrides: some authors are also administrators, so they need extra permissions that are normally denied to authors. I thought I could use this to "fall through" to the next role's permissions checks, perhaps.

If this option could be clarified, I'd really appreciate it.

**Comment by justintadlock** [comment]
I'd be happy to extend the docs if you or someone can think up some better wording.  Here's what they currently state:

> Granting a capability to a role means that users of that role will have permission to perform the given capability.
>
> Denying a capability means that the role's users are explicitly denied permission.
>
> A role that is neither granted nor denied a capability simply doesn't have that capability.

------

And, just a note on User Role Editor and other plugins:  capabilities in WordPress simply are not binary.  They are granted, denied, or not assigned to the role.

------

If you just need help with the plugin, hop on over to the [support forums](https://themehybrid.com/board/topics).

**Comment by courtneyschwartz** [comment]
Thanks for getting back so quickly.

Yes, I read them... but that's what I'm unable to decipher the meaning of. :(

How is  "Denying a capability" != "neither... doesn't have that a capability"?

It sounds the same. What's the difference?

It sounds like the simple "yes/no" on https://codex.wordpress.org/Roles_and_Capabilities is maybe not exactly true...? You would know the WP code for this better than I. If I can grasp it, I don't mind helping to massage text.

Essentially I'm creating this as a usability issue -- not necessarily yours, possibly show-through from WP core. If I could tell what's the intended behaviour, then I'd know if I had a config issue or not. Then I could definitely slot this as a PEBKAC and head to the forum...

**Comment by justintadlock** [comment]
Sorry, I missed the reply earlier.

> How is "Denying a capability" != "neither... doesn't have that a capability"?

Suppose you have two roles:  Super and Duper.  Here's what that looks like:

**Super:**

You want the Super role to allow users to:

- `edit_posts`

**Duper:**

You want the Duper role to:

- `edit_posts`
- `publish_posts`


Now, let's suppose you give user John both the Super and Duper roles.  Here are the total capabilities he'd have:

- `edit_posts`
- `publish_posts`

**Multiple roles:**

You create a user named John who has both the Super and Duper roles. Wait.  John has the Super role but you don't want Super users to ever be able to `publish_posts`.  Suddenly, you have an issue.  

You could create a third role.  Or, you could edit Super to explicitly **deny** that capability.  By denying it, John can no longer `publish_posts` despite also having the Duper role.
