### ISSUE TITLE
[members_access] restrict by user

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#179]
This was a feature request by a user.  The `[members_access]` shortcode should allow access based on:

* Username
* User Email
* User ID

**Comment by marcelreschke** [comment]
I would love to have `[members_access]` based on `if (is_user_logged_in() && $current_user->ID == $post->post_author)`.

**Comment by justintadlock** [comment]
Fixed in: https://github.com/justintadlock/members/commit/e1d5b1cdbb415276fd8dcf459c74eaecc3f0bc81
