### ISSUE TITLE
WP Multisite Bug: Notice: Undefined index: {CUSTOM_ROLL_NAME} in /wp-content/plugins/members/inc/functions-roles.php on line 250

### ISSUE THREAD

**Issue by mitcoding** [justintadlock/members#181]
Some background. I originally installed the members plugin on a single site install of wordpress (we will call site A) and created 4 new custom roles. The wordpress site has not launched yet. But during development I got the request that client needed multisite support. So I enabled multisite support on Site A. I then configured the multisite install with sub-directory configuration meaning we aren't usering subdomains. 

As far as I could tell everything was working fine. Until I created a new site in the network site admin of multisite (which we will call Site B). When I created the "Site B" I found that the roles that had originally been created in the "Site A" show up with this error in the roles screen:

Notice: Undefined index: {CUSTOM_ROLL_NAME} in /wp-content/plugins/members/inc/functions-roles.php on line 250

I also found that if I created a new role in "Site B" that the role would be created just fine but when I go into the "Site A's" role config panel I would now get the same error above for the newly created role on "Site B".

To summerize 

"Site A" created: 
"custom role 1"
"custom role 2"
"custom role 3"
"custom role 4"

"Site B" created:
"custom role 5"

On "Site A's" role config pannel custom roles 1-4 appear just fine. But on "Site B's" role config panel custom roles 1-4 show up with the error message above. While custom role 5 appears just fine on Site B's role config panel, on Site A custom role 5 shows up with the same error as custom role 1-4 does on "Site B".

Also I would like to point out if I try to create "Custom Role 5" in "Site A" to remove the error I get the message that the role already exists. Same if I try to re-create Custom Roles 1-4 on "Site B".

--Mitcoding

**Comment by mitcoding** [comment]
forgot to add. I'm running Wordpress 4.9.4, and Members 2.0.2

**Comment by justintadlock** [comment]
Anyone with a multisite install want to test this?  I don't use multisite, but I'd think this issue would be more prevalent with the number of folks running multisite + Members.

**Comment by mitcoding** [comment]
Am I correct to assume, that the custom member roles are supposed to be specific to each Site in a multisite? The reason I ask is when I go to the User Manger screen to bulk assign roles "Custom Role 5" is the only option on "Site B" along with the wordpress default roles. While Custom Roles 1-4 and the default wordpress roles are the only options in the Users manager screen's bulk assign options on "Site A".

**Comment by justintadlock** [comment]
Yes, roles in WordPress (Members doesn't actually create roles; it merely provides the interface for doing so) are specific to the site, not the entire network.  That's why I wonder how you could be seeing roles from Site A on Site B in the first place.

I assume you've tested with all other plugins deactivated as well, correct?

**Comment by mitcoding** [comment]
Yes, currently all plugins are deactivated except for Members (including Akismet Anti-Spam)

**Comment by mitcoding** [comment]
If I'm not even suppose to see custom roles from "Site A" in "Site B". Does that mean I should be able to create custom roles in "Site B" that have the same name as a custom role in "Site A"?

**Comment by justintadlock** [comment]
@mitcoding - I set up a multisite install and was able to reproduce the issue.  Can you give the latest from the 2.0 branch a test and let me know if it's working for you?

**Comment by mitcoding** [comment]
@justintadlock That patch did the trick. No more errors on role manager page and I can now create Custom Roles on "Site B" that have the same names as custom roles on "Site A". Now I just need to find a plugin that lets me sync the role settings between sites so I don't have migrate everything manually (any suggestions?).

**Comment by mitcoding** [comment]
@justintadlock - Thanks for the Quick Turnaround, that was awesomely fast. :)

**Comment by justintadlock** [comment]
I seem to recall someone building a sync role plugin a year or so ago.  I can't remember where I saw it.  

It might be an idea for an add-on plugin.  I just don't do any work with multisite, so I can't say something like that is a priority for me (I like to build stuff that I actually use -- otherwise, my heart's usually not in it).  It would be cool though, so I'll at least tack it onto my long list of ideas. :)

Anyway, I'm going to close out this ticket based on your feedback.
