### ISSUE TITLE
Unexpected behaviour with Members and WooCommerce (regarding my account section)

### ISSUE THREAD

**Issue by jorenmartijn** [justintadlock/members#182]
https://github.com/justintadlock/members/blob/e4dc8a82f10e9645e487aa3c104cf0faa90e5a48/inc/functions-private-site.php#L117

A while back I was setting up a WooCommerce shop on a development environment that also ran Members to display a login screen to unauthorised users.

All of a sudden we noticed the login screen stopped displaying after WooCommerce was installed.
It turned out the standard pages didn't get added like it usually does thus causing the`$page_id` variable to be empty within the WooCommerce compatibility check. What seems to happen is: when the `$page_id` variable is empty the `is_page()` function always returns true, on any page, which in turn disables the login screen. 

This can be solved by adding a extra check to the if statement that checks if the variable is not empty: `if(!empty($page_id) && is_page($page_id))` or something similar instead of `if(is_page($page_id))`.

I don't think this is a major issue in all fairness but it did throw me for a loop for a while trying to figure it out.

**Comment by justintadlock** [comment]
Good catch!  I'll make sure to get this into the next update.

**Comment by jorenmartijn** [comment]
Good to hear and thanks for picking this up so quickly. 👍
