### ISSUE TITLE
Trigger error if no $post_id in members_can_user_view_post()

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#183]
The biggest conflict that Members runs into with other plugins is those plugins calling `the_content` and other hooks outside of The Loop where the global `$post` should be available.  This ends up breaking Members.  Therefore, we should do two things:

* Bail if `$post_id` is not available.
* Trigger a `_doing_it_wrong()` error.

The error should inform that a plugin/theme has incorrectly applied a filter hook that should only be available in The Loop context.

It's also possible to call `members_can_user_view_post()` outside of The Loop if you pass in a custom `$post_id`.  That could also cause an error.  However, I've never had a support question about this.

**Comment by swissspidy** [comment]
Is there any chance that at least the notice reported in #188 could be fixed in a minor release? Somehow it's always triggered when saving a post in Gutenberg, which is quite annoying.

The fix is relatively easy, there just needs to be a check for the result of `get_post()` and if it's `null`, return early.

**Comment by justintadlock** [comment]
I'd think the best course of action would be to address this in the Gutenberg plugin.  I'd wager it is calling `apply_filters( 'the_content' )` when there's no global `$post` present.  If that's the case, it would break WP compatibility with a large number of plugins.

Reference: https://core.trac.wordpress.org/ticket/24330#comment:3

---

With that said, I'll certainly look into adding the above notice or bailing in a minor or patch release.

**Comment by jnaklaas** [comment]
Hi, fyi the PHP notice referenced above also happens when creating pages using wp cli.

```
$ wp post create --post_type=page --title="test"
PHP Notice:  Trying to get property 'post_parent' of non-object in [path]plugins/members/inc/template.php on line 95
Notice: Trying to get property 'post_parent' of non-object in [path]/plugins/members/inc/template.php on line 95`
Success: Created post 91.
