### ISSUE TITLE
Add-Ons Page Contains Invalid Thumbnail URL

### ISSUE THREAD

**Issue by leepeterson** [justintadlock/members#184]
`page=members-settings&view=add-ons` contains a reference to `http://img/addon.png` for the new Members - Admin Access add-on. I just updated the main Members plugin to see if it'd been updated with a fix, but it remains.

**Comment by leepeterson** [comment]
Side note: Members - Core Create Caps' thumbnail URL points to your Theme Hybrid domain. It works, but it seems like it should be pointing to the plugins' `/img/` folder containing other icons.

**Comment by justintadlock** [comment]
I've got some missing logic somewhere.  Basically, icons should go:

* If one is available in `members/img/addon-name.png`, use it.
* Check if one is available through the API (Theme Hybrid).
* Fall back to a default icon.

**Comment by justintadlock** [comment]
Should've been fixed in that last commit. Forgot to close.
