### ISSUE TITLE
Separate Super Admins from normal Admins?

### ISSUE THREAD

**Issue by joq3** [justintadlock/members#186]
Hi,

Just switched from User Role Editor to this plugin, but I cannot figure out if you can set different capabilities for normal Admins? I want Super Admin to ofcourse have all access, but I want to change some things with normal Admins.

This is on a Multisite network, I have network activated it.
Why doesn't it show up on the Network admin dashboard? Just on the main domain dashboard?

**Comment by justintadlock** [comment]
Super Admin is not a role in the same sense as "Administrator". Super Admins always have access to everything.
