### ISSUE TITLE
Cannot edit capabilities in sub-sites on multi-site platform

### ISSUE THREAD

**Issue by CharlesGodwin** [justintadlock/members#187]
I am using 2.0.2. I can easily add capabilities and edit role capabilities when working from the main site. But if I go to a sub-site, still logged in as super admin, I cannot edit any role capabilities in the sub-site Edit Roles page. I understand this for system wide roles such as Author etc. But If I define a role in the sub-site I cannot add or edit capabilities for these roles.
![members_subsite_problem](https://user-images.githubusercontent.com/20710431/37557424-cfbb4c80-29da-11e8-9552-2f4316d13057.png)

**Comment by justintadlock** [comment]
This sounds like a duplicate of https://github.com/justintadlock/members/issues/181.

Are you testing the latest 2.0 branch?  If not, grab a copy here: https://github.com/justintadlock/members/tree/2.0

**Comment by CharlesGodwin** [comment]
No. I am running 2.0.2 and as it's a live site I'd rather not use a test version. If you are planning to role this out in the next month, I'll wait. Otherwise I look into setting up a test site.

Thanks

**Comment by justintadlock** [comment]
Yes, I'm going to roll it out in the next week or two.  But, I'd need you or someone to test against that branch to make sure it's not the same issue.

**Comment by CharlesGodwin** [comment]
I'll investigate a test site. Remind me tomorrow if you don't get an update from me.

**Comment by CharlesGodwin** [comment]
I tested 2.0.2 on a plain multi-site and I cannot reproduce the problem. I tried network activated as it is on my production site and I tested with individual site activation. Both configurations worked as expected.

I will go back to my production site and see if I can find what's different.

This may take a day.

**Comment by CharlesGodwin** [comment]
I found the guilty party. It was a plugin named Prevent Direct Access Gold that we have just deleted for other reasons. Sorry for the trouble. 2.0.2 works as expected. I have not tests 2.0.3-dev.

**Comment by justintadlock** [comment]
Sounds good.  Thanks for digging into it.
