### ISSUE TITLE
PHP Notice: Trying to get property 'post_parent' of non-object

### ISSUE THREAD

**Issue by turtlepod** [justintadlock/members#188]
> [23-Mar-2018 16:29:25 UTC] PHP Notice:  Trying to get property 'post_parent' of non-object in ...\wp-content\plugins\members\inc\template.php on line 95

**Comment by justintadlock** [comment]
Closing in favor of: https://github.com/justintadlock/members/issues/183

**Comment by turtlepod** [comment]
Wow. that was quick!

**Comment by justintadlock** [comment]
This issue almost always comes up because the reasons outlined in this post: https://themehybrid.com/weblog/how-to-apply-content-filters
