### ISSUE TITLE
Profiling slow page generation - members accounts for over 8.32% of page generation time

### ISSUE THREAD

**Issue by ahmed-sigmalux** [justintadlock/members#191]
I'm profiling a website to figure out what's causing long (> 1s) page generation times. I've identified members as one of the culprits, as it accounts for at least 8.32% of the cost. The problematic calls are:

```
members_register_role @ 93	- 8.32%

members_role_registry()->register( $name, new \Members\Role( $name, $args ) );
```

Has anyone else profiled a website and identified the same issue? Is it normal for members to account for a significant portion of the page generation time?

**Comment by justintadlock** [comment]
That code should be pretty fast.  It's not doing much except for some fairly basic operations on data that WP has already loaded from the DB as far as I know.  It shouldn't come close to generating > 1s load times, even with a few hundred roles.

If you could dig further and can definitively find an issue directly with Members (I can't replicate it), I'd be happy to mark this ticket as a bug and make any necessary changes.  

The above is not much to go on, but I'll leave the ticket open for now pending further feedback.

**Comment by justintadlock** [comment]
Closing due to no feedback.
