### ISSUE TITLE
Set default access role

### ISSUE THREAD

**Issue by liyimeng** [justintadlock/members#193]
Today members will allow everyone to read your post if you don't set access roles explicitly.  This is inconvenient  for website that allow new user signup or run authentication with Oauth. 

I suggest member allow to set a default access role the post, prevent new signup user accessing unexacting content.

**Comment by justintadlock** [comment]
The `members_default_post_roles` hook is available for automatically checking roles on new posts.

The `members_can_user_view_post` hook is available for dynamically blocking a user's access to posts on the front end.
