### ISSUE TITLE
Link to the users list when editing a role

### ISSUE THREAD

**Issue by johnbillion** [justintadlock/members#197]
When editing a role, it would be handy to get back to the list of user with that role. Currently you need to go back to the Users screen, then click the user role filter. The `Users` text in the `Role` metabox when editing a role could link to the filtered list of users with that role.

**Comment by justintadlock** [comment]
Fixed in https://github.com/justintadlock/members/commit/d75a440ecfd2f376ab92a8e774416923dbc2816f

I'd like to look over a possible redesign of this box in 3.0.
