### ISSUE TITLE
Register Custom Caps I cannot

### ISSUE THREAD

**Issue by brandonkal** [justintadlock/members#202]
I would like to register a custom capability with the members media tab. This does not seem to work. Also, quickly scanning through this repo, I wasn't able to locate the list of capability tabs created. Adding this information to the README would be a helpful improvement.
Thank you.

```
// Register Custom Capabilites
add_role(
	'active-member', __( 'Active Member', 'plugin' ), [
		'read' => true,
		'watch_video' => true,
	]
);

add_action( 'members_register_caps', 'register_caps' );
function register_caps() {
	members_register_cap(
		'watch_video',
		[
			'label' => __( 'Watch Videos', 'plugin' ),
			'group' => 'Media',
		]
	);
}
```

**Comment by justintadlock** [comment]
Closing since this is a support question, which should be handled via support channels.
