### ISSUE TITLE
WP in debug mode, calling members_can_current_user_view_post() returns error

### ISSUE THREAD

**Issue by Josh68** [justintadlock/members#204]
Hello, and thanks for the great plugin.

In our local environment, I have been using `members_can_current_user_view_post()`, and, looking through source, see that you don't need to pass any params for the chained functions to be smart about getting the user and post IDs.

However, on a page that should 404, in development mode, this throws an error. It can be fixed by checking `get_the_ID()` thusly (for Timber):

```
$postID = get_the_ID();
$context['member_can_view']= $postID ? members_can_current_user_view_post($postID) : true;
```

Because I want all users to see 404s.

Is this worthy of a PR / fix? I started looking into issuing one, but didn't dig far enough to know whether there were reasons to not try to fix.

**Comment by justintadlock** [comment]
If you're calling the function in a scenario where there's no post ID, such as on a 404 page, then you're calling the function incorrectly.  It's only meant to be called in The Loop or with a post ID passed in.  I'd say letting this error out would be the right thing to do here.  This is a good error.

**Comment by Josh68** [comment]
In our case, we wanted a global way to provide this information at the page level to Timber context, so we put the check in an `add_to_context` callback on the `timber_context` filter: see the [Timber starter theme](https://github.com/timber/starter-theme/blob/master/functions.php). With our workaround, this seems to be a good solution.

Maybe this is simply a documentation issue: Noting in Timber starter and/or Members that there should be a check for `get_the_ID()` or `get_post()` before proceeding with adding values to context or checking role-based permissions. However, the fact that `members_can_current_user_view_post` can be called without either a `post_id` or `user_id` makes it a little vulnerable to this issue.

It's true that my assumption, that `members_can_current_user_view_post` should always return true when there is no post, depends on the use-case. I'd say it could be a valid assumption for a wrapper function  (e.g., `members_can_current_user_view_page`), only if you could know at the time of calling that a page-level `post_id` should be available.

So, in short, our workaround makes sense in our case, and not as a rule for the Members function. I'll close out this issue, but if you think anything should be added to Members documentation, let me know.
