### ISSUE TITLE
Capabilities for Custom Post Types

### ISSUE THREAD

**Issue by dgobnto** [justintadlock/members#205]
Hi,

I started using this plugin for a very simple feature but I don't seem to be able to set it up correctly.
All I'm looking for is to deny a user role all viewing, editing and publishing capabilities, except for one custom post type. Is it possible? Is this the right plugin for the job?

Thank you.

**Comment by justintadlock** [comment]
Closing this as invalid.  This is a support question and is better handled at https://themehybrid.com
