### ISSUE TITLE
Role names not showing up

### ISSUE THREAD

**Issue by annakolozsvari** [justintadlock/members#214]
Hi,
I couldn't find an issue related to this, but forgive me if I overlooked one.

The role names in user.php show up properly:
![image](https://user-images.githubusercontent.com/14539984/56283076-ac241c80-614b-11e9-9036-e2d5f33f3120.png)

But something really weird is happening on the roles page:
![image](https://user-images.githubusercontent.com/14539984/56283130-ca8a1800-614b-11e9-8708-e3ec7484677c.png)

Could you please explain why this is?
Thanks a lot!
Anna

**Comment by justintadlock** [comment]
Can you provide steps on how to reproduce this issue?

**Comment by annakolozsvari** [comment]
I guess this is the relevant line in my code:
$new_role = add_role($user_data['user_login'], $user_data['user_login']);

More details:
I create a new role for each new user (because I need to specify which pages each user can access).
The filter for this (that line is from here):
function create_role_for_newuser($user_data) {
	if(get_post()->post_name == 'new-user') {
		$new_role = add_role($user_data['user_login'], $user_data['user_login']);
		
		$allowed_page_ids = $_POST['reg_pages'];
		foreach((array) $allowed_page_ids as $page_id) {
			members_add_post_role($page_id, $new_role->name);
		}
		
		$user_data['role'] = $new_role->name;
		return $user_data;
	}
}
add_filter('woffice_register_user_data', 'create_role_for_newuser');

**Comment by annakolozsvari** [comment]
And this only happens when a username has a capital letter or special symbol (like @).

**Comment by justintadlock** [comment]
This is due to invalid characters.  You can change how role names are sanitized by hooking into `members_sanitize_role` and allowing the characters you want.
