### ISSUE TITLE
edit_post's capability power 

### ISSUE THREAD

**Issue by ridesirat** [justintadlock/members#215]
Hi Justin.
Best Roles Plugin ever.
I know you're in a rush for the 3.0.0 release.

Just wanted to "alert" you for this strange behavior in your plugin with Custom Post Types (CPT) - not the plugin before that.

Resuming:
When a user role has no edit_posts capability it can't use the featured image in Block Editor mode.
And now it's even worse, it can't edit any CPT post. The page appears blank - not even showing the dashboard top bar.

I've opened an [issue](https://github.com/WordPress/gutenberg/issues/12198) in Gutenberg but it's not getting any solution. It appears to be related to the REST-API - as @miya0001 says:

<ThemeSupportCheck> is checking that the theme supports post-thumbnail via REST-API.
But the REST-API needs edit_posts capability. So <ThemeSupportCheck> always returns false if user doesn't have this capability. (https://github.com/WordPress/gutenberg/issues/12198#issuecomment-478058975)

I would love to contribute to your plugin but I'm just a Designer with very low development knowledge.
Thanks and I hope this info helps.
(do you have a donation page or link? I really think the best developers should. I will gladly donate)

**Comment by justintadlock** [comment]
This looks like a core WordPress issue to me.  This ticket is linked to the Gutenberg issue you posted: https://core.trac.wordpress.org/ticket/46723

Members doesn't have any control over "what happens" (for lack of a better phrase) when a user has a given capability.  It merely allows you to assign capabilities to roles.  The "what happens" part is handled by WordPress.

I do have a donate page here: https://themehybrid.com/donate

**Comment by ridesirat** [comment]
Your right. Just thought it could help.
thanks.
(I'll try to contact you via your website to talk about the donation)
