### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by michaeledi** [justintadlock/members#216]
Hi Justin,
I found the php warning in the error log regarding members plugin:
“PHP message: PHP Warning: array_merge(): Expected parameter 1 to be an array, null given in …/wp-content/plugins/members/inc/functions-users.php on line 51”
“PHP message: PHP Warning: array_merge(): Expected parameter 1 to be an array, null given in …/wp-content/plugins/members/inc/functions-users.php on line 51”
“PHP message: PHP Warning: array_keys() expects parameter 1 to be array, null given in /data/wwwroot/facfox.com/wp-content/plugins/members/inc/functions-users.php on line 51”
“PHP message: PHP Warning: array_merge(): Expected parameter 2 to be an array, null given in /data/wwwroot/facfox.com/wp-content/plugins/members/inc/functions-users.php on line 51”

This warning has been generating constantly and frequently, making the php log extremly large, please review this issue and see if it’s a common one. Appreciate your effort!

**Comment by Mahjouba91** [comment]
Hey,

Your issue description should be PHP warnings and not errors.

Not so much activities in this repo for the past few months. Hope you have found a way to get rid of those warnings.
