### ISSUE TITLE
Few files contain Windows (CR+LF) line ends

### ISSUE THREAD

**Issue by szepeviktor** [justintadlock/members#220]
```
$ grep -Prl '\r' inc/ admin/ css/

inc/functions.php
inc/class-widget-users.php
inc/functions-private-site.php
admin/functions-admin.php
admin/class-meta-box-content-permissions.php
css/admin.css
```

**Comment by justintadlock** [comment]
I'm pretty sure _all_ of the files have Windows-style line endings, which mostly dates back to my early coding days when I didn't have any idea that other operating systems used something different.

This will all get converted over as I work on 3.0 with an `.editorconfig`, so I'm closing this one.

**Comment by szepeviktor** [comment]
Okay.

**Comment by szepeviktor** [comment]
@justintadlock Looking at 3.0 `namespace Members\Private;` may interfere with the [PHP reserved word](https://www.php.net/manual/en/reserved.keywords.php) `private`.
