### ISSUE TITLE
Display Login-Site only for sites with restricted access

### ISSUE THREAD

**Issue by Familien-Langen** [justintadlock/members#225]
Hi
I'm running a family site: https://familien-langen.net
For some pages I have set up restricted access, others are open to all visitors. I would like visitors who are not logged in to see the login page only when they want to reach a site with limited access. The sites that have no access restriction should be accessible to all visitors without login. Can you support me on how to set this up?

**Comment by saas786** [comment]
@Familien-Langen 

This plugin is more suitable for your needs: https://wordpress.org/plugins/restricted-site-access/

**Comment by Familien-Langen** [comment]
Hi @saas786 

Thanks for your feedback. Do you have experience to run this plugin parallel with the members plugin? Does that work?

**Comment by saas786** [comment]
Yes, we are using both Members + Restricted Site Access on our website.

**Comment by Familien-Langen** [comment]
Great, thanks for your consult. I'll try.

**Comment by Familien-Langen** [comment]
Hi @saas786 

Unfortunately, the plugin doesn't meet my requirements. By activating the plugin, the access to all sites is restricted.

I don't want all sites of the domain to be only accessible with login, f.e. the homepage https://familien-langen.net should be open for everybody. But there are some sites that have restricted access. I want the login only to be displayed for those sites.

**Comment by justintadlock** [comment]
Closing this ticket because this is an old repo (really need to archive this) and I'm no longer the owner of the plugin.  You'll need to reach out to the Caseproof/MemberPress team for help specific to Members: https://wordpress.org/plugins/members/
