### ISSUE TITLE
Support for per-user capabilities

### ISSUE THREAD

**Issue by robertirish** [justintadlock/members#23]
Hi @justintadlock 

I was wondering if as an enhancement, you could implement per-user capabilities? This would allow groups of users to access certain posts, but also for these groups to be flexible (some users from a group could access several kinds of posts, for example). This isn't possible using Roles without creating one for each user.

The PHP for achieving per-user roles is:

    $user = new WP_User( $user_id );
    $user->add_cap( $capability );

All the best and thanks for the fantastic plugin,

Robert

**Comment by justintadlock** [comment]
It looks like there's a little traction on that ticket.  There's a good patch right now that's going to open some doors.

Anyway, I'm going to close this ticket as I don't think per-user caps is the right approach.  We can revisit if there's ever any official word about per-user caps in core WP.
