### ISSUE TITLE
Admin capabilities missing/can't save

### ISSUE THREAD

**Issue by swhinnem** [justintadlock/members#27]
I'm using Members on a multisite instance, and I've added a few types of custom capabilities for CPTs. Somehow, the 'read' permission and a few others have been disabled for Administrators, resulting in them not having permissions to view wp-admin at all. 

I can enable them and save, but when I go back into the Admin role, they are disabled again. 

I've tried disabling the plugin, but it seems to persist in the DB- people with Administrator capabilities still can't log in.

**Comment by justintadlock** [comment]
Closing this one as I can't replicate the issue and it's out of date.  Feel free to reopen with more details if issue is still present.
