### ISSUE TITLE
Enhancement - Shortcode Display Member Error Instead of Blank/Nothing

### ISSUE THREAD

**Issue by jconroy** [justintadlock/members#3]
Hi Justin,

Question / Enhancement - Do you think it would be worth displaying non members an error or message when viewing content hidden by one of the members shortcodes?

So for example if I use [is_user_logged_in] to wrap (and hide) some member only content - instead of just displaying nothing it might be nice to show one of the member error messages. Like so -> https://github.com/FindingSimple/members/commit/ef8b2954e116a820afd17aa7ea9cc3e868522984

Perhaps for a nicer implementation the output could just be wrapped with a filter so that it can be hooked into within a theme or another plugin?

**Comment by drreen** [comment]
Gonna dig this one out. Any chance you will add custom error messages which can be triiggered by shortcode parameter near future?

**Comment by justintadlock** [comment]
Here's some problems that must be overcome and tested.

## Inline vs. block-level

The following is two example posts.  As you can see, one usage is inline and the other is block-level.  

**Post #1:**

	Hello world! [members_access capability="read"]How are you doing?[/members_access]

**Post #2:**

	Hello world!

	[members_access capability="read"]How are you doing?[/members_access]

## Content vs. parameter

You can add pretty much anything as the content of the shortcode, even HTML.  However, you can't add anything to a parameter.

**Allowed:**

	[members_access capability="read" error="What's up doc?"]<p>Oh, no! This is a paragraph.</p>[/members_access]

**Not Allowed:**

	[members_access capability="read" error="<p>What's up doc?</p>"]<p>Oh, no! This is a paragraph.</p>[/members_access]

**Comment by justintadlock** [comment]
One idea might be to introduce an additional parameter, such as `[members_access output="block"]` where `output` could be `block` or `inline`.  Or, something like that.  It's pretty much a nasty way to do it, but I'm not sure what else to do to allow an error message while handling the block vs. inline content issue.

The other option might simply be to let users go for two separate shortcodes (one for each of the two groups of users).  That seems easier to do.

**Comment by justintadlock** [comment]
Since Gutenberg is going to be the future editor, we should probably roll this into a custom access block.  See: #198

**Comment by justintadlock** [comment]
Given the issues I outlined above with the shortcode system and that this feature will be available in the Block Permissions add-on (see early screenshot below), I'm closing this ticket.

Ultimately, the block editor is the way forward and provides the necessary flexiblity for properly handling this.

![members-bp-003](https://user-images.githubusercontent.com/1816309/63227149-3c7d7700-c1a9-11e9-9f51-cd97e1025b4b.png)
