### ISSUE TITLE
Filter default roles for Content Permissions meta box

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#33]
Allow devs to filter the roles checked by default in the Content Permissions meta box.  Reference: https://wordpress.org/support/topic/default-content-permission-several-have-ask-no-answer

**Comment by lmartins** [comment]
I was just about to ask for this too :)

**Comment by justintadlock** [comment]
I haven't figured this out yet.  If I allow a plain filter on the roles array, we need a method of figuring out whether the post meta has been saved yet.

**Comment by justintadlock** [comment]
Just noting that I should utilize the method from ButterBean where the `load-post-new.php` hook determines if we're on a new post.  Thus, we can allow defaults to be set in that scenario.

**Comment by jjazzbel** [comment]
I am interested in this as well.  For now, adding the function in the child theme as described in the referenced post is working out for posts.  It could be more more elegant if handled at the plugin level.
