### ISSUE TITLE
Any plans to propagate pages permissions?

### ISSUE THREAD

**Issue by lmartins** [justintadlock/members#48]
Hi,
Is there any plans to add the option to propagate a page restriction to the corresponding child pages?

Thanks

**Comment by justintadlock** [comment]
I guess I do now. :)

I suppose I could check if a post type is hierarchical (e.g., pages).  Then, display a checkbox like this in the Content Permissions meta box:

	[ ] Apply permissions to child pages?

Then, if a child had its own permissions, it'd overrule the parent.

Sound like a plan?  Or, do you have something else in mind?

**Comment by lmartins** [comment]
Sounds exactly like I was hoping for. :)

**Comment by justintadlock** [comment]
I'm wondering if we should automatically do it rather than having another post setting.  I think it makes sense.  If a parent is protected, I can't think of a good reason that a child page is not protected.

Plus, it'd be far easier to deal with when it comes to non-hierarchical post types that have children (e.g., forums, topics, and replies).

I'll post some code soon for testing.

**Comment by justintadlock** [comment]
Check the latest commit above to test this feature.  Basically, child posts (of any post type) will automatically inherit its parent permissions **if** the child post itself doesn't have any specific permissions of its own.

This feature can disabled with a simple filter:

	add_filter( 'members_check_parent_post_permission', '__return_false' );

Or, developers can take it further with a more elaborate filter:

	add_filter( 'members_check_parent_post_permission', 'my_check_parent', 10, 3 );

	function my_check_parent( $check, $post_id, $user_id ) {

		// Do something based on $post_id and/or $user_id parameters.

		return $check;
	}

**Comment by lmartins** [comment]
Wow @justintadlock didn't expected this to land so fast. I was on the fence about which plugin to use for this, not anymore.

Regarding your question above, from my understanding I believe having the child posts protected by default (if parent protected) is a quite reasonable default, and I think what people want most of time anyway.

I'll be testing this version during the day, will let you know if I find any issues.

Thanks again man!  :)

**Comment by justintadlock** [comment]
I'm actually in the middle of a big overhaul of the plugin, so loads of changes are happening on the `dev` branch at the moment.  You happened to catch me at the right time.  Plus, several others have asked about this. :)

**Comment by lmartins** [comment]
Lucky me ... and thank you again. :)  Should I close this now or do you want to keep it open for reference about the decisions you're considering?

**Comment by justintadlock** [comment]
If it's working for you, go ahead and close.  I left it open for testing.

**Comment by lmartins** [comment]
It is, although I don't see any option to control wether the subpages should or should not inherit the parent setting. But I've tested it and it is closing the access to all the child pages.

**Comment by justintadlock** [comment]
I decided against adding an option for it by default.  I added a filter for developers to enable/disable the feature instead.  We can revisit the idea of an option later based on feedback.
