### ISSUE TITLE
Redirect to content after login

### ISSUE THREAD

**Issue by lmartins** [justintadlock/members#50]
Would it be possible for the login widget to redirect the user to the previous page, instead of the Dashboard?

**Comment by nemchik** [comment]
I've noticed this is also an issue when I set my entire site to members only. all logins redirect to the dashboard rather than the page the user tried to visit.
This would be very appreciated.

**Comment by justintadlock** [comment]
@nemchik - That is a different issue than the login widget.  While I'm here though, I can say that is a WP issue, not a Members issue.  WP should redirect you back to the correct page.

**Comment by justintadlock** [comment]
I'm closing this because I haven't  been able to reproduce the issue.
