### ISSUE TITLE
Role clone

### ISSUE THREAD

**Issue by m-e-h** [justintadlock/members#51]
I realize you're actively working on the dev branch (like a couple hours ago actively). But just in case you weren't aware, I just noticed I no longer see an option to clone.

**Comment by justintadlock** [comment]
It's appearing for me on the latest commit.  Do you have the `create_roles` cap?

I'm also testing against WP 4.3.

**Comment by m-e-h** [comment]
That's the commit I was on. I was on a 4.2 multi-site. I'll check again later this evening.

**Comment by m-e-h** [comment]
Yep, it works with 4.3.
Tried it on a couple 4.2 installs and got the same results - no options on hover. Updated to 4.3 and the options are there `Edit | Delete | Clone | Users`

**Comment by justintadlock** [comment]
Cool.  I'm going to close this then.  The next version of Members is going to 4.3+ only.
