### ISSUE TITLE
Shortcode not working

### ISSUE THREAD

**Issue by ajman825** [justintadlock/members#56]
Not sure why, content in shortcode `[members_access role=""]` just don't show up. Not sure if that's related to `members_user_has_role()` require the user ID as well? I made some changes locally on `functions-shortcodes.php:128`

**Comment by justintadlock** [comment]
Try the dev copy to see if that corrects the issue: https://github.com/justintadlock/members/tree/dev

**Comment by ajman825** [comment]
Resolved, cool ;)
