### ISSUE TITLE
v 0.2.5 to v 1.0.2 has broken media(attachment) permissions UI

### ISSUE THREAD

**Issue by fyaconiello** [justintadlock/members#57]
The UI for controlling permissions on media no longer shows, however, the permissions previously configured still work.

![Example of the UI I am referring to](https://cloud.githubusercontent.com/assets/227515/9971363/48465b8e-5e29-11e5-89c0-cc737d37e6db.png)

**Comment by justintadlock** [comment]
This is the intended behavior.  Too many folks misunderstood what the "content" part of "content permissions" meant when it came to attachments, so the UI is disabled by default.

**Comment by fyaconiello** [comment]
Is there a supported way of reenabling this UI for previous installs that rely on this feature? Also, was this change documented in the release notes? We had a bit of a race to figure out what had changed and why.
