### ISSUE TITLE
Add actions to content permissions metabox

### ISSUE THREAD

**Issue by richardtape** [justintadlock/members#59]
PR https://github.com/justintadlock/members/pull/58 adds an action at the top and bottom of the content permissions metabox allowing us to hook in here and add other ways in which the content can be restricted. I'm building a way to join the members plugin and JJJ's [WP User Groups plugin](https://wordpress.org/plugins/wp-user-groups)

**Comment by justintadlock** [comment]
I'm cool with adding in any needed hooks.  We should probably stick to "before/after" nomenclature.  Something like:

	do_action( 'members_content_permissions_meta_box_before', $post );

That's a bit lengthy though, so might need to go with:

	do_action( 'members_cp_meta_box_before', $post );

**Comment by justintadlock** [comment]
By the way, I closed the PR since it needed discussion first and was against the master branch.

New features need to be added to minor releases as well (would be added to version 1.1.0).  Version 1.0.3, if it happens, would be a patch release to fix bugs.

**Comment by richardtape** [comment]
Urgh. I'm an idiot. I genuinely looked for guidelines for PRs but somehow missed the contrib file. Genuine apologies. Also, I take your point w.r.t before/after and the length.

As you're happy with adding in hooks, I'll take that as an ok to create a new PR from the dev branch. That'll be incoming soon. Again, sorry for being blind.

**Comment by richardtape** [comment]
https://github.com/justintadlock/members/pull/60 adjusts the PR as outlined above

**Comment by justintadlock** [comment]
PR looks good except we need to change `metabox` to two words like `meta_box`.

**Comment by richardtape** [comment]
Nice spot. Adjusted.

**Comment by justintadlock** [comment]
Cool. It's in now.
