### ISSUE TITLE
Link capabilities to WordPress Codex page

### ISSUE THREAD

**Issue by nemchik** [justintadlock/members#62]
Can the capabilities editor display links for the capabilities to the WordPress Codex page for that capability? For example https://codex.wordpress.org/Roles_and_Capabilities#read

**Comment by justintadlock** [comment]
Like #61, this would need an appropriate UI built that would accommodate such a link. 

I'm not sure it would work as individual cap links. But, I could see a single "?" icon in the top right of the edit caps box working.

**Comment by nemchik** [comment]
I like the single "?" idea! That page doesn't display a ton of information about the individual capabilities, so it makes sense to have the link only once just to direct people to the page explaining causalities overall.

**Comment by justintadlock** [comment]
I'm thinking the best course of action here is to simply link to the Roles and Capabilities page in the Codex in the "Help" tab at the top of the screen.
