### ISSUE TITLE
"All" cap group should include caps from all groups

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#67]
Currently, the "all" cap group doesn't take into account capabilities from post types and taxonomies that are not assigned to roles or those from custom groups.

See: https://github.com/justintadlock/members/pull/66#issuecomment-143825847

**Comment by justintadlock** [comment]
@styledev - Can I get you to check this on the 1.0 branch? It should fix the issue you brought up.

**Comment by styledev** [comment]
@justintadlock - I have confirmed that the latest commit for branch 1.0 fixes this issue.

**Comment by justintadlock** [comment]
Cool. Thanks for letting me know.
