### ISSUE TITLE
Cap groups should have a priority argument

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#69]
Cap groups should be have a priority argument. That way, plugin authors can customize the order or simply move their group to a higher position.

**Comment by zackkatz** [comment]
:+1:

**Comment by justintadlock** [comment]
Note: Use the object priority sorter from ButterBean.  Should make this easy.

**Comment by justintadlock** [comment]
Fixed in https://github.com/justintadlock/members/commit/a3e992db032ff3f2aa8ee7b9cb7027c20d5f3743
