### ISSUE TITLE
Allow Editor to edit other user's Roles but not grant Administrator

### ISSUE THREAD

**Issue by deweydb** [justintadlock/members#71]
I have a user role: "Editor".  I gave them the capability of: "promote_users" so that they could add certain roles to other lower users who do not have this capability.  But how do i prevent these editor's from promoting themselves to a higher role like "administrator" because right now they can choose any roles they want for anybody.

**Comment by justintadlock** [comment]
Please see the [readme](https://github.com/justintadlock/members/blob/master/readme.md#the-relationship-of-users-roles-and-capabilities).  **Roles are not hierarchical.**  There is no such thing as a "higher" role.  I also recommend reading the [article](http://justintadlock.com/archives/2009/08/30/users-roles-and-capabilities-in-wordpress) (also linked in the readme) that I wrote that explains this in great depth.

If you want hierarchical roles, you'll need a plugin that makes them hierarchical.

**Comment by deweydb** [comment]
Will this plugin work along side your members plugin? or will there be conflicts?
https://wordpress.org/plugins/user-hierarchy/

**Comment by justintadlock** [comment]
No idea. I'd like to build an add-on for Members though to handle a role hierarchy.

**Comment by deweydb** [comment]
That would be pretty amazing! in my mind this is a pretty big gap in wordpress' ability to be as robust of a CMS as say Drupal.

**Comment by justintadlock** [comment]
I actually think the opposite.  I believe non-hierarchical roles are much more robust and flexible, at least out of the box.

Nevertheless, hierarchical roles are obviously something that some folks need.

**Comment by deweydb** [comment]
Well would there be some sort of hook or filter i could use to just block editors from assigning that one role (administrator) ?
