### ISSUE TITLE
members_can_user_view_post returns notice on custom endpoint

### ISSUE THREAD

**Issue by fprezat** [justintadlock/members#72]
When reaching a custom endpoint with a rewriting api, we have a notice in members_can_user_view_post function :
````
<b>Notice</b>:  Trying to get property of non-object in <b>.../wp-content/plugins/members/inc/template.php</b> on line <b>97</b>
````

When creating a custom endpoint, we are not in a wp loop, so the function get_the_ID return false and the line get_post( $post_id )->post_parent return a notice

Thank you for your help

**Comment by justintadlock** [comment]
By default, Members only fires the `members_can_user_view_post()` function when `the_content` filter hook is called.  This is a very specific hook in WP meant to be used when `the_content()` function is fired.  `the_content()` is only ever meant to be used within the loop.

It sounds like your plugin might be calling either `the_content()` or `apply_filters( 'the_content' )` incorrectly.

**Comment by fprezat** [comment]
We have built a poo class for an external api, which fire this code :
````
$article_content = apply_filters( 'the_content', $article_content );
````

So we are not in a loop context, fetching the content from the database and keeping all filters on the content.

**Comment by justintadlock** [comment]
Your plugin shouldn't be calling `the_content` like that in that case.  You should do something like this instead:

	$article_content = apply_filters( 'my_prefix_content', $article_content );

Then, apply any filters you want to apply.  Here's an example: https://github.com/justintadlock/whistles/blob/master/inc/class-whistles-and-bells.php#L56

**Comment by justintadlock** [comment]
Also, just for reference from one of the lead developers of WordPress: https://core.trac.wordpress.org/ticket/24330#comment:3

**Comment by justintadlock** [comment]
I wrote a tutorial on this if it helps: http://themehybrid.com/weblog/how-to-apply-content-filters

**Comment by fprezat** [comment]
Thank you, it helps me a lot !
