### ISSUE TITLE
Allow dashes in role names

### ISSUE THREAD

**Issue by clifgriffin** [justintadlock/members#73]
`members_sanitize_role` converts all dashes to underscores, which causes problems with existing roles that have dashes in their slugs, and plugins which add roles with dashes in the slug. 

This doesn't seem to be an actual WordPress requirement, though I can understand it stylistically. I'd recommend not sanitizing existing roles.  Sanitization can be used for new roles.

Does that sound like a fair solution?

**Comment by justintadlock** [comment]
I'm inclined to close this as the plugin has, for 6 years, asked for only alphanumeric characters and underscores.  I'd have to dig into what potential issues allowing for hyphens might cause.  I definitely won't be sanitizing new roles while skipping old ones, which would open us up to several security issues.

In the meantime, you can always filter `members_sanitize_role`.

**Comment by clifgriffin** [comment]
@justintadlock Yeah, I've been using it for about as long as was surprised to run into this. 

The role in question is a role included in Shopp by default. So I get that it can be filtered, but in general I'm not sure why we would not exclude role slugs already in the DB from sanization or how that would open up a security problem.

Happy to put together a PR if that would be helpful :)

**Comment by justintadlock** [comment]
> So I get that it can be filtered, but in general I'm not sure why we would not exclude role slugs already in the DB from sanization or how that would open up a security problem.

You're making an assumption that existing roles are in the DB, which is not necessarily the case.  For example, I personally have a plugin that creates dynamic roles on the fly that are not saved in the database at all.

Even if they do exist in the database, it's wrong to assume that the data is safe.

All roles must be sanitized/validated the same.  They're used in various ways, such as URLs, attributes, and other places.

> Happy to put together a PR if that would be helpful :)

I don't need a PR.  It's a simple enough change.  I just need time to think about any potential issues and for testing.

**Comment by justintadlock** [comment]
`members_sanitize_role()` now allows for a hyphen.  However, the JS when creating a new role will still attempt to kill off any hyphens.  This should correct the issue with existing roles. See: https://github.com/justintadlock/members/commit/8ce42a14c76ac40f8d8510cbd19e4c58c5a8d0ea

I still encourage passing along to any plugin authors using hyphens that they really should use underscores instead.

**Comment by clifgriffin** [comment]
Sweet. Thanks!





On Sat, Jan 9, 2016 at 12:04 PM -0800, "Justin Tadlock" <notifications@github.com> wrote:












members_sanitize_role() now allows for a hyphen.  However, the JS when creating a new role will still attempt to kill off any hyphens.  This should correct the issue with existing roles. See: 8ce42a1



I still encourage passing along to any plugin authors using hyphens that they really should use underscores instead.
