### ISSUE TITLE
Make page / post textarea for non-members WYSIWYG

### ISSUE THREAD

**Issue by yratof** [justintadlock/members#74]
The textarea on a page or post that allows you to show a custom message is just a plain textarea, yet the same textarea in the settings is a wysiwyg editor. Could the single page also have the abilities that the settings page possesses?
- A WYSIWYG editor instead of a text area, the same as the wysiwyg in the settings for Members
- Additional: A login form shortcode, allowing you yo embed the login form without needing a sidebar in the design

**Comment by justintadlock** [comment]
Please create separate tickets for separate feature requests..

The WP editor class can't be put into a metabox because metaboxes can be moved.  This causes issues with the editor, which is a bug that's outside the scope of Members.  This is simply a non-starter until that's fixed in WP.

As for the login form, use `[members_login_form]`.

**Comment by yratof** [comment]
Ahh of course – I think thats out of wordpress’ scope too, as they use tinymce for the wysiwyg – The one thing that I would say to look at is how Advanced Custom Fields manage their wysiwyg within metaboxes – it’s either worth implementing despite the drawback of moving the metabox freezes it, or it’s removed – the contrast between “style it however you want” and “here’s a textbox” might be too much

**Comment by justintadlock** [comment]
I'm going to be revisiting this in the _nearish_ future.  It might make the version 2.0.0 cut.

**Comment by justintadlock** [comment]
I'm going to redesign the meta box if anyone thinks the UI needs a little sprucing with the above commit.  So, I'm closing this ticket as fixed.
