### ISSUE TITLE
Check if user can read current Post/Page

### ISSUE THREAD

**Issue by lmartins** [justintadlock/members#78]
I need to hide additional elements of a specific page that is restricted to a given role.
Do I need in that case to create a custom capability as described in https://github.com/justintadlock/members#checking-if-the-current-user-has-a-capability or does Members provide any sort of template tag for that?

**Comment by justintadlock** [comment]
Closing this as invalid because it's a support question.  Support is handled via: http://themehybrid.com/board/topics
