### ISSUE TITLE
Typos in Admin screen

### ISSUE THREAD

**Issue by FuzzyBo** [justintadlock/members#79]
The following were found when doing a Translation of Stable (latest release): English (Australia).

Text at admin/class-meta-box-content-permissions.php:149† says "Custom error messsage:". There is a triple "s" in message, which should have a double "s".

Text at admin/class-meta-box-content-permissions.php:151† says "Message shown to users that do no have permission to view the post.". I suggest it should say "not" rather than "no"

† In the code viewable in this repository, the line numbers are 156 and 158

**Comment by justintadlock** [comment]
That last commit should correct those.  I plan on pushing out an update for the plugin this week.
