### ISSUE TITLE
All Roles Unchecked When Editing Profile

### ISSUE THREAD

**Issue by cgrymala** [justintadlock/members#82]
When I edit a user's profile, all of the "User Roles" are unchecked. If I save the user's profile without re-checking the appropriate role, that user's role gets removed.

This appears to be related to the way the plugin checks the user roles in the [`profile_fields()` method](https://github.com/justintadlock/members/blob/master/admin/class-user-edit.php#L79).

When I dump the `$user` var on my site, the `roles` property is empty. However, the `caps` property contains the name of the role that needs to be checked.

As a result, I manually modified my copy of the plugin in the following way:

Line 79:
Change 
`$user_roles = (array) $user->roles;` 
to 
`$user_roles = (array) $user->roles;
$user_caps = (array) $user->caps;`

Line 99 (now line 100 after adding the extra line above):
Change 
`<input type="checkbox" name="members_user_roles[]" value="<?php echo esc_attr( $role ); ?>" <?php checked( in_array( $role, $user_roles ) ); ?> />` 
to 
`<input type="checkbox" name="members_user_roles[]" value="<?php echo esc_attr( $role ); ?>" <?php checked( array_key_exists( $role, $user_caps ) || in_array( $role, $user_roles ) ? true : false ); ?> />`

In this case, I am running WordPress Multisite, so that may or may not be why the roles array is empty, but I wanted to make you aware of the issue. Thanks.

I am currently running version 1.1.1 of Members on WordPress 4.4.1 with multisite enabled. In any of the cases I've noticed, I've been editing another user's profile while I'm set as a Network Admin for the installation and I'm explicitly set as an Administrator for the sub-site.

**Comment by justintadlock** [comment]
I cannot replicate this issue.  My recommendation would be to deactivate all other plugins for testing.

**Comment by cgrymala** [comment]
You're absolutely right. For some reason, it seems to be related to the [Types](https://wordpress.org/plugins/types/) plugin. I'm not sure why, but I'll try to investigate further. Thanks, and I apologize for filing an erroneous issue.

**Comment by cgrymala** [comment]
In case anyone is interested, I've filed a possible bug report with Types at https://wp-types.com/forums/topic/possible-bug-a-users-role-is-unset-on-the-profile-edit-page/

**Comment by justintadlock** [comment]
Ah, I remember there was an issue with Types a couple of months back.  It was my understanding that they had a fix that was supposed to be put out in their next release.

**Comment by justintadlock** [comment]
I wrote a lengthier explanation on the WordPress.org support forums for others to see.  It also describes some other issues I'm seeing in the code. https://wordpress.org/support/topic/multiple-roles-roles-not-checked-or-not-saving
