### ISSUE TITLE
Private Site - BuddyPress New User Activation Link Whitelist

### ISSUE THREAD

**Issue by turtlepod** [justintadlock/members#83]
Currently members only check registration page:
https://github.com/justintadlock/members/blob/master/inc/functions-private-site.php#L68

It need to check user activation page too. example:
https://github.com/turtlepod/fx-private-site/blob/1.0.1/includes/functions.php#L73

you can also check using `bp_is_activation_page()` and `bp_is_register_page()`
( functions located at: "bp-core/bp-core-template.php" )

**Comment by justintadlock** [comment]
Can you test this on the `dev` branch, @turtlepod?  I don't run BuddyPress.

**Comment by turtlepod** [comment]
I actually don't run buddypress too.
And it was actually reported by one of my plugin user,
https://genbumedia.com/2016/02/01/fx-private-site-updated-to-v-1-0-1/

but your code seems fine.

**Comment by justintadlock** [comment]
Going to close this then.

**Comment by paulgibbs** [comment]
Hello. Was updating this plugin for a client site, then saw this change.

These functions will work, but I'd suggest switching them out for `bp_is_activation_page()` and `bp_is_register_page()`. The implementation is the same under the hood, but if we change the implementation in the future, this would stop working.

**Comment by justintadlock** [comment]
New ticket, please.  Otherwise, I won't notice this closed ticket when I come back around to updating the plugin.
