### ISSUE TITLE
Private (sub) site visible to multisite logged in users 

### ISSUE THREAD

**Issue by mfindlayated** [justintadlock/members#87]
Hi,

We are seeing an issue with the members plugin in a multisite installation; when the 'Private site' functionality is switched on in a sub site.

If you are a logged on member of the multisite, but are not a user of the specific sub site, the content is still viewable.

Should "private site' restrict access to posts on sub sites, where the user has a WP account, but not for the particular sub site?

I did wonder if maybe anopther plugin was causing the issue (we also use Groups), but rebuilt our TEST site with only the members plugin installed, and still see the issue.

Thanks in advance,
Mark.

**Comment by justintadlock** [comment]
Actually, the feature is not meant to restrict sub-sites and such.  It's meant to only check if  user is logged in.

We could change this though for multisite.  There are two issues at play that would need to be solved:

* How to determine if the user is allowed to see the site.
* Where to redirect a logged-in user without access (current redirect to login screen).

**Comment by justintadlock** [comment]
Anyone got ideas on this?  I rarely work with multisite.

**Comment by ammist** [comment]
Hi @justintadlock!  Thanks for directing me here from the forums.  I'm working on building this feature for an intranet I'm doing, so I'm happy to share once I get to a solution.

To answer your questions above:

- We can use current_user_can('read') to check to see if the logged-in user has read permissions on the current site (e.g. is at least a Subscriber).
- This would require an option to be set for the "You don't have access to this site" page.  It could default to the WordPress "You can't do that" screen but that's unfriendly.  Hm.  Okay, let me think more about it.

**Comment by justintadlock** [comment]
> We can use `current_user_can('read')` to check to see if the logged-in user has read permissions on the current site (e.g. is at least a Subscriber).

That's actually not a bad idea if there's not a more appropriate core function.  I'd need to limit it specifically to multisite to limit any potential damage for anyone who's doing anything odd with the `read` cap.

**Comment by giaschel** [comment]
I'm also looking for this feature to block only a subsite.

On multisite installations, one can install a plugin on the whole network of sites or only on one particular site. Would that be of any help? I have no programming knowledge, sorry.

**Comment by ammist** [comment]
Hi all,

Here's a function I wrote to implement this.  Perhaps this can be of use to you.

`// Prevent logged-in users from seeing content when site that has been flagged as "Private"
// though Members setting.  This function will take logged-in users to a page on the parent site
// that explains the issue.
add_action( 'template_redirect', 'intranet_private_site_redirect', 2 );
function intranet_private_site_redirect(){
	if (! is_user_logged_in()) return;
	
	if (function_exists('members_is_private_blog') && members_is_private_blog()){
		// private blog!
		if (!current_user_can('read') ){
			wp_redirect('/restricted-access');  // should be an option
			exit(1);
		}	
	}

	return;

}
`

**Comment by justintadlock** [comment]
An option for setting the redirect page is not necessarily something one site admin from another site might know.  Sure, if you're in control of the entire network, that's OK.  

I'm imagining something like Site A redirecting to Site B for users without access.  Then, the Site B owner redirects users without access to site A.  You get a continual redirect from one site to another.

One thing I have in mind is seeing if there's a core WP function for getting all of a user's sites.  Then, just grabbing the first one and auto-redirecting there.

**Comment by ammist** [comment]
Indeed.  In our situation, we have an intranet, so we ARE in control of the whole network - and one of the pages on the default site has some forms for people to request access, so this solution worked great for us. 

I also considered doing something where the whole site is protected, EXCEPT the page that explains that you can't have access, which proved more complicated than time allowed, but is theoretically possible.

If the main site has to be a private site, this solution obviously doesn't work, BTW.

What might work is to take the user to their profile page on a site where they DO have access, and put some explanatory text there.

Here's the function for getting a user's sites: https://developer.wordpress.org/reference/functions/get_blogs_of_user/

**Comment by justintadlock** [comment]
One thing we could do is redirect to one of the user's blogs.  If they don't have a blog, which I believe is a legit thing, then `wp_die()`.

I could also add in a filter hook for devs to control the URL to redirect to.

**Comment by justintadlock** [comment]
Or, instead of redirecting, just `wp_die()` and list all blogs the user has access to with a message that the current blog is private.

**Comment by justintadlock** [comment]
Can I get some folks to test the above commit on the `dev` branch?  I don't have a multisite set up at the moment and could really use the feedback.

Primarily, I need to know whether it actually works correctly.  

Other than that, feedback on the handling is welcome.

**Comment by justintadlock** [comment]
I'm closing this as fixed at this point.  Feel free to comment here if I need to reopen.

**Comment by ammist** [comment]
Thank you Justin!  I tested this with our site over the weekend and it looks good.
