### ISSUE TITLE
Clone role

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/members#9]
Quick link under the role name on the roles list table to clone a role.  This link should copy the caps for whatever role is selected and take the user to the add new role page.  From there, they can save or customize then save.

**Comment by marisqaporter** [comment]
Is there supposed to be a quick link under the role name that says clone or dupe? Not in my version. Or am I misunderstanding the above?

![clone](https://cloud.githubusercontent.com/assets/9387224/5925296/85e4baa0-a630-11e4-9e95-e6b6e4cbfc6e.png)

**Comment by justintadlock** [comment]
No. This is an open issue for a future version.

**Comment by marisqaporter** [comment]
Oh I see. I found the hardcode way to do it. Thanks!

**Comment by justintadlock** [comment]
Fixed: https://github.com/justintadlock/members/commit/f8644ecae7451f55c2280df0bdb38e35c9f1b129
