### ISSUE TITLE
Nested shortcodes for member_access

### ISSUE THREAD

**Issue by Pokerkoffer** [justintadlock/members#94]
Hello,
feature suggestion:
Use nested shortcodes for members_access
```
[members_access role="level-a"]
This content can be seen by users with role "level-a"

 [members_access-1 role="level-b"]
 This content can be seen by users with role "level-a" and "level-b"
 [/members_access-1]

[/members_access]
```

See https://github.com/Pokerkoffer/members/commit/d43691a8a24d99691be6952770763af562f57463

**Comment by justintadlock** [comment]
Like I said in #92, this one is pretty much dead on arrival.
