### ISSUE TITLE
Filter to add exceptions to private site setting

### ISSUE THREAD

**Issue by jbvidex** [justintadlock/members#95]
When you have the private site setting enabled, and have something (like WooCommerce) that hijacks the default password reset functionality, users are unable to recover a lost password. Could we get a filter that would allow us to except certain pages from the blanket login requirement?

**Comment by justintadlock** [comment]
The great thing about WP is that it comes with built-in hooks for everything.  Like options:

        add_filter( 'option_members_settings', 'my_members_settings' );

        function my_members_settings( $settings ) {

        	if ( some_conditional_func() )
        		$settings['private_blog'] = false;

        	return $settings;
        }

I can build in a more obvious filter hook though. :)
