### ISSUE TITLE
Content permissions metabox info text

### ISSUE THREAD

**Issue by lutrov** [justintadlock/members#96]
If would good for usability if the content permissions metabox info text used the term "page" and the custom post type names instead of defaulting to "post" in all cases.

In `class-meta-box-content-permissions.php`, right now there are two places where the word "post" is used:

> "Limit access to this post's content to users of the selected roles."
> 
> "If no roles are selected, everyone can view the content. The post author, any users who can edit this post, and users with the restrict_content capability can view the content regardless of role."

For pages, ideally it should read like this:

> "Limit access to this page's content to users of the selected roles."
> 
> "If no roles are selected, everyone can view the content. The page author, any users who can edit this page, and users with the restrict_content capability can view the content regardless of role."

If I had a CPT called "movie" for instance, ideally it should read like this:

> "Limit access to this movie's content to users of the selected roles."
> 
> "If no roles are selected, everyone can view the content. The movie author, any users who can edit this movie, and users with the restrict_content capability can view the content regardless of role."

**Comment by justintadlock** [comment]
There's no way to get the `page's` and `movie's` text in a translation-friendly way.  Same with `page` and `movie`.  There are no existing post type labels for those forms of the post types.

It could be improved though.  Maybe something without all the extra text to begin with.  The UI should speak for itself if at all possible.

**Comment by lutrov** [comment]
There is `singular_name` but yeah, you're right, there's no accounting for `movies' or `movie's`. What about a filter that allows us to change the whole sentence then? That would work.

**Comment by justintadlock** [comment]
`singular_name` is typically uppercase (in English), not lowercase.  While `strotolower()` would work for many English post type names, it would be inconsistent across languages and not account for words that should be uppercase.

It's usually bad form to provide filter hooks for text strings (that's what translation files are for).  If it comes down to it, I'll use that option as a last resort.

A simple change in the text might suffice:

> "Limit access to the content to users of the selected roles."
>
> "If no roles are selected, everyone can view the content. The author, any users who can edit the content, and users with the `restrict_content` capability can view the content regardless of role."

I'd like to cut back on the wording though and simplify it.

**Comment by lutrov** [comment]
Yes, that will work. Using "content" still keeps it meaningful, irrespective of whether it's a page, post, movie, etc. I think your text is good and I can't see how it could be simplified while still being explanatory. Thanks for taking the time to discuss it.
