### ISSUE TITLE
(has patch) Multiple roles checkboxes for new users

### ISSUE THREAD

**Issue by mhull** [justintadlock/members#97]
I noticed this is missing, and you had mentioned that you just hadn't gotten to it yet.

I use Members all the time, love it and wanted to contribute back.  I have a fork where I've added this functionality, if you're interesting in checking it out:

https://github.com/mhull/members/tree/dev

**Comment by justintadlock** [comment]
I plan on looking at this more in-depth once I get a nice block of time to test it out.

**Comment by mhull** [comment]
Cool.  I am more than happy to work on modifications if you have feedback/suggestions.  

I didn't do a ton of stuff, mainly added additional hooks for your already existent functions.  The one questionable thing I believe might be using JS to remove the existing role <select> element.  Maybe use admin_print_scripts instead of enqueueing a whole new file?

**Comment by justintadlock** [comment]
Just linking to the specific commit so I'll know where it's at: https://github.com/mhull/members/commit/99d896e7c4e5ff9b754f53899c3bc437ab9e1797

The code looks basic enough.

**Comment by justintadlock** [comment]
@mhull - Thanks for the starting point on this.  It was a huge help.
