### ISSUE TITLE
Tag Input in custom post type admin page not displaying

### ISSUE THREAD

**Issue by nkostic** [justintadlock/members#99]
When we assign more than one role to the user, default tag input in custom post type admin page is not displaying anymore, you can only see the header with title but no input. When we revert back the same user to only one role, input "tag" is there and working.

This is how tag input looks like when we set the two roles
![tag not workin](https://cloud.githubusercontent.com/assets/426266/16094693/a9c0c5e8-32fe-11e6-91c5-cbbc7a1c36e5.png)

This is how it looks like when we have only one role
![tag working](https://cloud.githubusercontent.com/assets/426266/16094702/af43176e-32fe-11e6-8aa3-ed7944c70be9.png)

**Comment by justintadlock** [comment]
This means your user doesn't have permission to assign terms.

**Comment by nkostic** [comment]
I am pretty sure they both have same permissions related to custom post types and standard posts. I will try to get more answers on codex. Thank You.

**Comment by nkostic** [comment]
I just figured out what happen and you where right. Thank You for the great plugin and sorry about the invalid bug report.
